getopt doesn't work in all systems when used in a conditional
When running
  if PARSE=$(getopt...);then
it always triggers the conditional. This behavior is contradictory to
what is expected. Investigating for now leaving old style.

diff --git a/vim-pack-export b/vim-pack-export
--- a/vim-pack-export
+++ b/vim-pack-export
@@ -13,15 +13,14 @@ LONG=help,silent,git-dir:
 getopt --test > /dev/null
 supports_long_opts=$(( $? == 4 ))
 if [[ $supports_long_opts == true ]]; then
-	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
 else
-	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
 fi
 
 eval set -- "$PARSED"
@@ -92,7 +91,7 @@ for i in {opt,start}; do
 	repos_folders=$(ls "$repo_dir/$i/")
 	for j in $repos_folders; do
 		url=$(git -C "$repo_dir/$i/$j" remote get-url origin)
-		if [[ "$ofile_specified" = true ]]; then
+		if [[ "$ofile_specified" == true ]]; then
 			repo_list+="[$j]\n"
 			repo_list+="	dir = $i/$j\n"
 			repo_list+="	url = $url\n"
diff --git a/vim-pack-import b/vim-pack-import
--- a/vim-pack-import
+++ b/vim-pack-import
@@ -15,15 +15,14 @@ LONG=help,silent,git-dir:
 getopt --test > /dev/null
 supports_long_opts=$(( $? == 4 ))
 if [[ $supports_long_opts == true ]]; then
-	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
 else
-	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
 fi
 
 eval set -- "$PARSED"
@@ -84,7 +83,7 @@ for sec in ${INI__ALL_SECTIONS}; do
 	repo_target=${!v}
 	v="INI__${sec}__dir"
 	dest_name=${!v}
-	if [ "$silent" = true ]; then
+	if [ "$silent" == true ]; then
 		git clone "$repo_target" "$repo_dir/$dest_name" > /dev/null
 	else
 		git clone "$repo_target" "$repo_dir/$dest_name"
diff --git a/vim-pack-remove b/vim-pack-remove
--- a/vim-pack-remove
+++ b/vim-pack-remove
@@ -12,15 +12,14 @@ LONG=help,silent,git-dir:
 getopt --test > /dev/null
 supports_long_opts=$(( $? == 4 ))
 if [[ $supports_long_opts == true ]]; then
-	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then 
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
 else
-	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
 fi
 
 eval set -- "$PARSED"
diff --git a/vim-pack-upgrade b/vim-pack-upgrade
--- a/vim-pack-upgrade
+++ b/vim-pack-upgrade
@@ -1,4 +1,8 @@
 #! /usr/bin/env bash
+has_parallel=true
+if (which parallel); then
+	has_parallel=false
+fi
 repo_dir=$HOME/.vim/pack/git-plugins
 silent=false
 
@@ -6,19 +10,18 @@ silent=false
 # This handles the optional arguments
 ###
 SHORT=hsd:
-LONG=hsilent,git-dir:
+LONG=help,silent,git-dir:
 getopt --test > /dev/null
 supports_long_opts=$(( $? == 4 ))
 if [[ $supports_long_opts == true ]]; then
-	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
 else
-	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
-		echo 'Failed to parse arguments'
-		exit 2
-	fi
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
 fi
 
 eval set -- "$PARSED"
@@ -26,6 +29,7 @@ while true; do
 	case "$1" in
 		-h|--help)
 			usage=true
+			echo hello
 			break
 			;;
 		-d|--git-dir)
