Added -h usage/help flag

diff --git a/vim-pack-export b/vim-pack-export
--- a/vim-pack-export
+++ b/vim-pack-export
@@ -7,25 +7,30 @@ silent=false
 ###
 ofile_specified=false
 
-SHORT=sd:
-LONG=silent,git-dir:
+SHORT=hsd:
+LONG=help,silent,git-dir:
 
 getopt --test > /dev/null
-if (( $? == 4 )); then
-	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+supports_long_opts=$(( $? == 4 ))
+if [[ $supports_long_opts == true ]]; then
+	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 else
-	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 fi
-
-if (( $? != 0 )); then
-	echo 'Failed to parse arguments'
-	exit 2
-fi
-
 
 eval set -- "$PARSED"
 while true; do
 	case "$1" in
+		-h|--help)
+			usage=true
+			break
+			;;
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -43,6 +48,34 @@ while true; do
 			;;
 	esac
 done
+if [[ $usage == true ]]; then
+	echo 'usage: vim-pack export [-s|--silent] [-d <dir>| --git-dir=<dir>] [<file>]'
+	echo 'usage: vim-pack list   [-s|--silent] [-d <dir>| --git-dir=<dir>] [<file>]'
+	echo
+	echo
+	echo '       If <file> is provided then the list of packages will be exported to a file'
+	echo '       following the INI file format. If the -s or --silent option arguments are'
+	echo '       given then an output file is mandatory. This is useful for transferring '
+	echo '       configurations across machines and for listing all installed packages'
+	echo
+	echo 'Options:'
+	echo '    -s| --silent'
+	echo '        To hide output that normally goes to stdout'
+	echo
+	echo '    -d <dir> | --git-dir=<dir>'
+	echo '        Specify the name for the package director by default it is'
+	echo '        $HOME/.vim/pack/git-plugins'
+	echo
+	echo 'Note:'
+	echo '       Long options are only available with systems that have an enhanced version'
+	echo '       of getopt.'
+	if [[ $supports_long_opts == true ]]; then
+		echo '       This system DOES support long options'
+	else
+		echo '       This system DOES NOT support long options'
+	fi
+	exit 0
+fi
 
 if [[ ! -z "$1" ]]; then
 	outfile=$1
@@ -76,3 +109,4 @@ if [[ "$ofile_specified" == true ]]; then
 fi
 
 exit 0
+
diff --git a/vim-pack-get b/vim-pack-get
--- a/vim-pack-get
+++ b/vim-pack-get
@@ -7,23 +7,30 @@ silent=false
 # This handles the optional arguments
 ###
 
-SHORT=sd:
-LONG=silent,git-dir:
-getopt --test > /dev/null
-if (( $? == 4 )); then
-	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
-else
-	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
-fi
+SHORT=hsd:
+LONG=help,silent,git-dir:
 
-if (( $? != 0 )); then
-	echo "Failed to parse arguments"
-	exit 2
+getopt --test > /dev/null
+supports_long_opts=$(( $? == 4 ))
+if [[ $supports_long_opts == true ]]; then
+	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
+		echo "Failed to parse arguments"
+		exit 2
+	fi
+else
+	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
+		echo "Failed to parse arguments"
+		exit 2
+	fi
 fi
 
 eval set -- "$PARSED"
 while true; do
 	case "$1" in
+		-h|--help)
+			usage=true
+			break
+			;;
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -41,6 +48,39 @@ while true; do
 			;;
 	esac
 done
+
+if [[ $usage == true ]]; then
+	echo 'usage: vim-pack get     [-s|--silent] [-d <dir>| --git-dir=<dir>] <opt|start> <URL> [<new name>]'
+	echo 'usage: vim-pack install [-s|--silent] [-d <dir>| --git-dir=<dir>] <opt|start> <URL> [<new name>]'
+	echo
+	echo 'use <opt> or <start> to specify whether it should be a optional package or'
+	echo 'loaded for every time if you use <opt> you will need to specifically add the'
+	echo 'package using the vim 8 command "packadd <package name>"'
+	echo
+	echo '<URL> specifies the directory the package should be pulled from. Internally'
+	echo 'this is a git clone command'
+	echo
+	echo '[<new name>] can be used if you would like to load the package under a'
+	echo 'different name'
+	echo
+	echo 'options:'
+	echo '    -s| --silent'
+	echo '        to hide output that normally goes to stdout'
+	echo
+	echo '    -d <dir> | --git-dir=<dir>'
+	echo '        specify the name for the package directory by default it is'
+	echo '        $home/.vim/pack/git-plugins'
+	echo
+	echo 'note:'
+	echo '       long options are only available with systems that have an enhanced version'
+	echo '       of getopt.'
+	if [[ $supports_long_opts == true ]]; then
+		echo '       this system does support long options'
+	else
+		echo '       this system does not support long options'
+	fi
+	exit 0
+fi
 
 start_opt=$1
 repo_target=$2
diff --git a/vim-pack-import b/vim-pack-import
--- a/vim-pack-import
+++ b/vim-pack-import
@@ -9,24 +9,30 @@ silent=false
 # This handles the optional arguments
 ###
 
-SHORT=sd:
-LONG=silent,git-dir:
+SHORT=hsd:
+LONG=help,silent,git-dir:
 
 getopt --test > /dev/null
-if (( $? == 4 )); then
-	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+supports_long_opts=$(( $? == 4 ))
+if [[ $supports_long_opts == true ]]; then
+	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 else
-	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
-fi
-
-if (( $? != 0 )); then
-	echo 'Failed to parse arguments'
-	exit 2
+	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 fi
 
 eval set -- "$PARSED"
 while true; do
 	case "$1" in
+		-h|--help)
+			usage=true
+			break
+			;;
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -44,6 +50,31 @@ while true; do
 			;;
 	esac
 done
+
+if [[ $usage == true ]]; then
+	echo 'vim-pack import [-s|--silent] [-d <dir>| --git-dir=<dir>] <file>'
+	echo
+	echo '<file> is the name of the required INI format file. This can be generated using vim-pack export this is useful for'
+	echo 'transferring configurations between machines.'
+	echo 
+	echo 'options:'
+	echo '    -s| --silent'
+	echo '        to hide output that normally goes to stdout'
+	echo
+	echo '    -d <dir> | --git-dir=<dir>'
+	echo '        specify the name for the package director by default it is'
+	echo '        $HOME/.vim/pack/git-plugins'
+	echo
+	echo 'note:'
+	echo '       long options are only available with systems that have an enhanced version'
+	echo '       of getopt.'
+	if [[ $supports_long_opts == true ]]; then
+		echo '       this system does support long options'
+	else
+		echo '       this system does not support long options'
+	fi
+	exit 0
+fi
 
 import_file=$1
 read_ini "$import_file"
diff --git a/vim-pack-remove b/vim-pack-remove
--- a/vim-pack-remove
+++ b/vim-pack-remove
@@ -7,24 +7,29 @@ silent=false
 # This handles the optional arguments
 ###
 
-SHORT=sd:
-LONG=silent,git-dir:
+SHORT=hsd:
+LONG=help,silent,git-dir:
 getopt --test > /dev/null
-if (( $? == 4 )); then
-	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+supports_long_opts=$(( $? == 4 ))
+if [[ $supports_long_opts == true ]]; then
+	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then 
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 else
-	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 fi
-
-if (( $? != 0 )); then
-	echo 'Failed to parse arguments'
-	exit 2
-fi
-
 
 eval set -- "$PARSED"
 while true; do
 	case "$1" in 
+		-h|--help)
+			usage=true
+			break
+			;;
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -42,6 +47,29 @@ while true; do
 			;;
 	esac
 done
+if [[ $usage == true ]]; then
+	echo 'usage: vim-pack remove [-s|--silent] [-d <dir>| --git-dir=<dir>] [<opt|start>] <name>'
+	echo
+	echo '<name> specifies the package name'
+	echo
+	echo 'options:'
+	echo '    -s| --silent'
+	echo '        to hide output that normally goes to stdout'
+	echo
+	echo '    -d <dir> | --git-dir=<dir>'
+	echo '        specify the name for the package director by default it is'
+	echo '        $HOME/.vim/pack/git-plugins'
+	echo
+	echo 'note:'
+	echo '       long options are only available with systems that have an enhanced version'
+	echo '       of getopt.'
+	if [[ $supports_long_opts == true ]]; then
+		echo '       this system does support long options'
+	else
+		echo '       this system does not support long options'
+	fi
+	exit 0
+fi
 
 if (( $# == 2 )); then
 	start_opt=$1
diff --git a/vim-pack-upgrade b/vim-pack-upgrade
--- a/vim-pack-upgrade
+++ b/vim-pack-upgrade
@@ -5,23 +5,29 @@ silent=false
 ####
 # This handles the optional arguments
 ###
-SHORT=sd:o:
-LONG=silent,git-dir:,output:
+SHORT=hsd:
+LONG=hsilent,git-dir:
 getopt --test > /dev/null
-if (( $? == 4 )); then
-	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+supports_long_opts=$(( $? == 4 ))
+if [[ $supports_long_opts == true ]]; then
+	if PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 else
-	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
-fi
-
-if (( $? != 0 )); then
-	echo 'Failed to parse arguments'
-	exit 2
+	if PARSED=$(getopt --options $SHORT --name "$0" -- "$@"); then
+		echo 'Failed to parse arguments'
+		exit 2
+	fi
 fi
 
 eval set -- "$PARSED"
 while true; do
 	case "$1" in
+		-h|--help)
+			usage=true
+			break
+			;;
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -40,6 +46,27 @@ while true; do
 			;;
 	esac
 done
+if [[ $usage == true ]]; then
+	echo 'usage: vim-pack upgrade [-s|--silent] [-d <dir>| --git-dir=<dir>]'
+	echo
+	echo 'options:'
+	echo '    -s| --silent'
+	echo '        to hide output that normally goes to stdout'
+	echo
+	echo '    -d <dir> | --git-dir=<dir>'
+	echo '        specify the name for the package directory by default it is'
+	echo '        $home/.vim/pack/git-plugins'
+	echo
+	echo 'note:'
+	echo '       long options are only available with systems that have an enhanced version'
+	echo '       of getopt.'
+	if [[ $supports_long_opts == true ]]; then
+		echo '       this system does support long options'
+	else
+		echo '       this system does not support long options'
+	fi
+	exit 0
+fi
 
 if [[ "$silent" == true ]]; then
 	for i in {opt,start}; do
