getopt old version test and practice fixes
Fixed a swath of bad practices in my bash code
Fixed the getopt test so that if it doesn't support long arguments then
it will not try to use them.

diff --git a/vim-pack-export b/vim-pack-export
--- a/vim-pack-export
+++ b/vim-pack-export
@@ -6,18 +6,19 @@ silent=false
 # This handles the optional arguments
 ###
 ofile_specified=false
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-	echo "$(getopt --test) failed in this environment."
-	exit 1
-fi
 
 SHORT=sd:
 LONG=silent,git-dir:
-PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
 
-if [[ $? -ne 0 ]]; then
-	echo "Failed to parse arguments"
+getopt --test > /dev/null
+if (( $? == 4 )); then
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+else
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
 	exit 2
 fi
 
@@ -38,39 +39,40 @@ while true; do
 			break
 			;;
 		*)
-			break;
+			break
 			;;
 	esac
 done
-if [ ! -z "$1" ]; then
+
+if [[ ! -z "$1" ]]; then
 	outfile=$1
 	ofile_specified=true
 fi
-if [ "$silent" = true ] && [ "$ofile_specified" = false ]; then
+if [[ "$silent" == true ]] && [[ "$ofile_specified" == false ]]; then
 	echo "Cannot export silent without a output file specified"
 	echo "Provide an output file"
 	exit 1
 fi
 
-repo_list=""
+repo_list=''
 for i in {opt,start}; do
-	repos_folders=$(ls $repo_dir/$i/)
+	repos_folders=$(ls "$repo_dir/$i/")
 	for j in $repos_folders; do
 		url=$(git -C "$repo_dir/$i/$j" remote get-url origin)
-		if [ "$ofile_specified" = true ]; then
+		if [[ "$ofile_specified" = true ]]; then
 			repo_list+="[$j]\n"
 			repo_list+="	dir = $i/$j\n"
 			repo_list+="	url = $url\n"
 		fi
-		if [ "$silent" = false ]; then
+		if [[ "$silent" == false ]]; then
 			echo "[$j]"
 			echo "	dir = $i/$j"
 			echo "	url = $url"
 		fi
 	done
 done
-if [ "$ofile_specified" = true ]; then
+if [[ "$ofile_specified" == true ]]; then
 	echo -e "$repo_list" > "$outfile"
 fi
 
-exit 0;
+exit 0
diff --git a/vim-pack-get b/vim-pack-get
--- a/vim-pack-get
+++ b/vim-pack-get
@@ -6,24 +6,24 @@ silent=false
 ####
 # This handles the optional arguments
 ###
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-    echo "$(getopt --test) failed in this environment."
-    exit 1
-fi
 
 SHORT=sd:
 LONG=silent,git-dir:
-PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+getopt --test > /dev/null
+if (( $? == 4 )); then
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+else
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
 
-if [[ $? -ne 0 ]]; then
-		echo "Failed to parse arguments"
-    exit 2
+if (( $? != 0 )); then
+	echo "Failed to parse arguments"
+	exit 2
 fi
 
 eval set -- "$PARSED"
 while true; do
-	case "$1" in 
+	case "$1" in
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -51,10 +51,10 @@ echo "$repo_target"
 echo "$dest_name"
 
 cd "$repo_dir/$start_opt"
-if [ "$silent" = true ]; then 
-	git clone $repo_target $dest_name > /dev/null
+if [[ "$silent" == true ]]; then
+	git clone "$repo_target" "$dest_name" > /dev/null
 else
-	git clone $repo_target $dest_name
+	git clone "$repo_target" "$dest_name"
 fi
 
 exit $?
diff --git a/vim-pack-import b/vim-pack-import
--- a/vim-pack-import
+++ b/vim-pack-import
@@ -1,5 +1,5 @@
 #! /usr/bin/env bash
-my_dir="$(dirname $(readlink "$0"))"
+my_dir="$(dirname "$(readlink "$0")")"
 source "$my_dir/bash_ini_parser/read_ini.sh"
 repo_dir=$HOME/.vim/pack/git-plugins
 silent=false
@@ -8,24 +8,25 @@ silent=false
 ####
 # This handles the optional arguments
 ###
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-    echo "$(getopt --test) failed in this environment."
-    exit 1
-fi
 
 SHORT=sd:
 LONG=silent,git-dir:
-PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
 
-if [[ $? -ne 0 ]]; then
-		echo "Failed to parse arguments"
-    exit 2
+getopt --test > /dev/null
+if (( $? == 4 )); then
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+else
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
+fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
 fi
 
 eval set -- "$PARSED"
 while true; do
-	case "$1" in 
+	case "$1" in
 		-d|--git-dir)
 			repo_dir=$2
 			shift 2
@@ -45,17 +46,17 @@ while true; do
 done
 
 import_file=$1
-read_ini $import_file
+read_ini "$import_file"
 
 for sec in ${INI__ALL_SECTIONS}; do
 	v="INI__${sec}__url"
 	repo_target=${!v}
 	v="INI__${sec}__dir"
 	dest_name=${!v}
-	if [ "$silent" = true ]; then 
-		git clone $repo_target $repo_dir/$dest_name > /dev/null
+	if [ "$silent" = true ]; then
+		git clone "$repo_target" "$repo_dir/$dest_name" > /dev/null
 	else
-		git clone $repo_target $repo_dir/$dest_name
+		git clone "$repo_target" "$repo_dir/$dest_name"
 	fi
 done
 
diff --git a/vim-pack-remove b/vim-pack-remove
--- a/vim-pack-remove
+++ b/vim-pack-remove
@@ -1,25 +1,26 @@
 #! /usr/bin/env bash
-repo_dir=$HOME/.vim/pack/git-plugins
+repo_dir="$HOME/.vim/pack/git-plugins"
 silent=false
 
 
 ####
 # This handles the optional arguments
 ###
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-    echo "$(getopt --test) failed in this environment."
-    exit 1
-fi
 
 SHORT=sd:
 LONG=silent,git-dir:
-PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
-
-if [[ $? -ne 0 ]]; then
-		echo "Failed to parse arguments"
-    exit 2
+getopt --test > /dev/null
+if (( $? == 4 )); then
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+else
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
 fi
+
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
+fi
+
 
 eval set -- "$PARSED"
 while true; do
@@ -42,17 +43,17 @@ while true; do
 	esac
 done
 
-if [[ $# -eq 2 ]]; then
+if (( $# == 2 )); then
 	start_opt=$1
 	pack_name=$2
-	if [ "$silent" = true ]; then 
-		rm -rf "$repo_dir/$start_opt/$pack_name" > /dev/null
+	if [[ "$silent" == true ]]; then 
+		rm -rf "${repo_dir:?}/$start_opt/$pack_name" > /dev/null
 	else
-		rm -rf "$repo_dir/$start_opt/$pack_name"
+		rm -rf "${repo_dir:?}/$start_opt/$pack_name"
 	fi
-elif [[ $# -eq 1 ]]; then
+elif (( $# == 1 )); then
 	pack_name=$1
-	if [ "$silent" = true ]; then 
+	if [[ "$silent" == true ]]; then 
 		rm -rf "$repo_dir/start/$pack_name" > /dev/null
 		rm -rf "$repo_dir/opt/$pack_name" > /dev/null
 	else
diff --git a/vim-pack-update b/vim-pack-update
--- a/vim-pack-update
+++ b/vim-pack-update
@@ -5,21 +5,19 @@ silent=false
 ####
 # This handles the optional arguments
 ###
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-	echo "$(getopt --test) failed in this environment."
-	exit 1
-fi
-
 SHORT=sd:
 LONG=silent,git-dir:
-PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
-
-if [[ $? -ne 0 ]]; then
-	echo "Failed to parse arguments"
-	exit 2
+getopt --test > /dev/null
+if (( $? == 4 )); then
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+else
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
 fi
 
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
+fi
 
 eval set -- "$PARSED"
 while true; do
@@ -45,7 +43,7 @@ done
 
 update_count=$(( 0 ))
 update_list=""
-if [ "$silent" = true ]; then
+if [[ "$silent" == true ]]; then
 	for i in {opt,start}; do
 		for j in $repo_dir/$i/*/; do
 			git -C "$j" fetch > /dev/null
@@ -61,7 +59,7 @@ else
 		for j in $repo_dir/$i/*; do
 			echo "$j"
 			git -C "$j" fetch
-			_ahead=$(git -C "$j" rev-list "HEAD..@{u}" | wc -l)
+			_ahead=$(git -C "$j" rev-list 'HEAD..@{u}' | wc -l)
 			if (( _ahead > 0 )); then
 				update_count=$(( update_count + 1 ))
 				update_list="$update_list ${j#"$repo_dir/$i/"}"
@@ -70,9 +68,9 @@ else
 	done
 fi
 if (( update_count > 0 )); then
-	echo "Updates available for:"
+	echo 'Updates available for:'
 	echo "  $update_list"
 else
-	echo "No updates available"
+	echo 'No updates available'
 fi
-exit 0;
+exit 0
diff --git a/vim-pack-upgrade b/vim-pack-upgrade
--- a/vim-pack-upgrade
+++ b/vim-pack-upgrade
@@ -5,21 +5,19 @@ silent=false
 ####
 # This handles the optional arguments
 ###
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-	echo "$(getopt --test) failed in this environment."
-	exit 1
-fi
-
 SHORT=sd:o:
 LONG=silent,git-dir:,output:
-PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
-
-if [[ $? -ne 0 ]]; then
-	echo "Failed to parse arguments"
-	exit 2
+getopt --test > /dev/null
+if (( $? == 4 )); then
+	PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+else
+	PARSED=$(getopt --options $SHORT --name "$0" -- "$@")
 fi
 
+if (( $? != 0 )); then
+	echo 'Failed to parse arguments'
+	exit 2
+fi
 
 eval set -- "$PARSED"
 while true; do
@@ -32,10 +30,6 @@ while true; do
 			silent=true
 			shift
 			;;
-		-o|--output)
-			outfile=$2
-			shift 2
-			;;
 		--)
 			shift
 			break
@@ -47,7 +41,7 @@ while true; do
 	esac
 done
 
-if [ "$silent" = true ]; then
+if [[ "$silent" == true ]]; then
 	for i in {opt,start}; do
 		for j in $repo_dir/$i/*/; do
 			git -C "$j" pull > /dev/null
@@ -62,4 +56,4 @@ else
 	done
 fi
 
-exit 0;
+exit 0
